### ISSUE TITLE
'message': 'The registration token is not a valid FCM registration token'

### ISSUE THREAD

**Issue by FjoralbIsmolli** [healthjoy/async-firebase#15]
I tried to send a push notification to my Android device, but I get the following response:
{'error': {'code': 400, 'message': 'The registration token is not a valid FCM registration token', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.firebase.fcm.v1.FcmError', 'errorCode': 'INVALID_ARGUMENT'}]}}

Any help on that?

**Comment by akalex** [comment]
@FjoralbIsmolli AFAIK, that usually means the device token that has been used is no longer valid (expired to be more precise).

**Comment by FjoralbIsmolli** [comment]
How do we get the device token though?

**Comment by akalex** [comment]
The token is retrieved by the device, here is the complete [documentation](https://firebase.google.com/docs/cloud-messaging/android/client) of how that happens with examples. Once the device retrieved the token it could be used to send push notifications using this client.

**Comment by akalex** [comment]
@FjoralbIsmolli hey, should you have any other questions or me may close the issue?
