### ISSUE TITLE
Hope add MulticastMessage support

### ISSUE THREAD

**Issue by yswtrue** [healthjoy/async-firebase#19]

**Comment by akalex** [comment]
Hey, @yswtrue thanks for posting the request. I am gonna prioritize some work on that.

**Comment by akalex** [comment]
https://github.com/healthjoy/async-firebase/pull/20

**Comment by akalex** [comment]
The support of MulticastMessage has been added to version 1.9.0. I am gone close this issue.

**Comment by yswtrue** [comment]
Thank you very much.
