### ISSUE TITLE
Will add support of add class of response like firebase-admin

### ISSUE THREAD

**Issue by yswtrue** [healthjoy/async-firebase#21]
It only returns a json and sometime it's hard to develop

**Comment by akalex** [comment]
@yswtrue AFAIK, Firebase is not verbose in its response, so What other information you might be looking for?

**Comment by akalex** [comment]
Got it, that makes sense, I am gonna add this.

**Comment by yswtrue** [comment]
Thank you

**Comment by akalex** [comment]
@yswtrue this is done https://github.com/healthjoy/async-firebase/pull/25, thanks to @ndmytro
