### ISSUE TITLE
Image argument for Notification object

### ISSUE THREAD

**Issue by dbhathena** [healthjoy/async-firebase#34]
**Is your feature request related to a problem? Please describe.**
The [Firebase Notification object](https://firebase.google.com/docs/reference/admin/python/firebase_admin.messaging#notification) in the python Admin SDK is able to take in an "image" argument to display as part of the notification. I would like to be able to use this field when constructing a notification with the async-firebase library as well.

**Describe the solution you'd like**
The async-firebase Notification object should accept title, body, and image arguments to match the underlying Firebase Notification object

**Describe alternatives you've considered**
Alternatives would just involve not using the async library and reverting to using the Firebase Notification object, but I would miss the functionality of this library!

**Additional context**
N/A

**Comment by akalex** [comment]
@dbhathena Thanks for posting this. I'll take care of it.

**Comment by akalex** [comment]
PR https://github.com/healthjoy/async-firebase/pull/35

**Comment by akalex** [comment]
Added in version [v2.1.0](https://github.com/healthjoy/async-firebase/releases/tag/v2.1.0)
