### ISSUE TITLE
Improve Push Multicast to take a list of messages

### ISSUE THREAD

**Issue by GENL** [healthjoy/async-firebase#50]
First of all, thank you for this great job.

I want to send multicast push notifications to hundreds of devices and each device has a specific `notification_count` also the motivation body could include the name of the device's user. With the current implementation of `push_multicast()`, it's impossible as the function only takes a list of device tokens, not a list of `bodies` and `notification_count`. 

The solution I propose is to make `push_multicast()` accept a list of Messages, similar to what firebase_admin does with the `send_all()` function. This fixes the issue because each message can be personalized.

For now, the only alternative I used was to call hundreds of `push()` by chunks of 10 in a loop. This is at the cost of performance. I expect it to be a temporary solution.

**Comment by akalex** [comment]
Hello @GENL,
Thanks for the feature request, I'll take care of it.

**Comment by GENL** [comment]
Thank you @akalex, very well done. Already migrated to this new version.
