### ISSUE TITLE
[Question] Limits has no effect?

### ISSUE THREAD

**Issue by svidchenkov-a** [healthjoy/async-firebase#66]
I probably get it wrong, but it looks like Limits for client have no effect because we [create](https://github.com/healthjoy/async-firebase/blob/master/async_firebase/base.py#L183) a new httpx.AsyncClient with each AsyncClientBase.send_request call.
I want to limit number of connections to FCM by limiting the number of connections in httpx connection pool, but appereantly for this to work we need to reuse httpx.AsyncClient beetween send_request calls

btw. @akalex thank you for your great work.

**Comment by akalex** [comment]
Hi @svidchenkov-a,
Thanks for submitting a question. You are correct; in the current implementation, `Limits` have no effect. Let me fix that.
