### ISSUE TITLE
send_multicast causes 404 response

### ISSUE THREAD

**Issue by Narquadah** [healthjoy/async-firebase#68]
**Describe the bug**
404 Response when using `send_multicast` using the newest version. It works fine on `3.3.0`.

**To Reproduce**
Use `send_multicast` method.

**Additional context**
Logs:
```
[INFO] HTTP Request: POST https://oauth2.googleapis.com/token "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST https://fcm.googleapis.com/v1/projects/xxxxxxxxx/messages%3Asend/batch "HTTP/1.1 404 Not Found"
[WARNING] Unexpected HTTP response with status: 404; body: b''
```

Thanks!

**Comment by akalex** [comment]
Hello @Narquadah,
I will take a look at it.
