### ISSUE TITLE
404 on send_each_for_multicast

### ISSUE THREAD

**Issue by COSHW** [healthjoy/async-firebase#73]
Recently, when sending multicast message, AsyncFirebaseClient would close the event loop and stop working further. 

I did some digging myself and found out, that it happens because of 404 response when making a "message:send" request. 
Discovered cause of this was async_firebase/utils.py:49 util that has encoded a ":" symbol into "%3A", resulting in a 404 response. 

Removing quote fixed the issue.

![image](https://github.com/healthjoy/async-firebase/assets/45237915/0585fa42-73ca-4ac6-9be4-b3e2a9deddfc)

**Comment by ndmytro** [comment]
@COSHW thanks for bringing this up, I will take a look shortly
